name: lazy_dm_helper
description: "A database application to help D&D DM's access data more easily."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  firebase_auth: ^4.19.4
  logger: ^2.2.0
  firebase_core: ^2.30.1
  flutter_bloc: ^8.1.5
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  http: ^1.2.1
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0
  firebase_core_platform_interface: ^5.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/.env
  fonts:
    - family: JakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans.ttf